### ISSUE TITLE
Use `/dbinfo` instead of hardcoding instance info in nginx config

### ISSUE THREAD

**Issue by jkuester** [jkuester/couch-with-metrics#4]
When connecting to an external CHT instance, we are currently hardcoding the instance information in the nginx config (because the the root `/` of the Couch instance is not available behind the CHT api).  

Instead of hardcoding the instance information, the nginx config should just redirect the root requests from the exporter to the `/dbinfo` CHT endpoint. That will serve up the expected instance information.

**Comment by mrjones-plip** [comment]
If for any reason the Prometheus exporter doesn't play nice with the `301` or `302`, we could do a rewrite so that `/` is revers proxied to `/dbinfo`.  Either are WAY better than the hard coded static JSON we have now!
